### ISSUE TITLE
Projectable is ignoring my indent level

### ISSUE THREAD

**Issue by AlexChesters** [domtronn/projectable.el#9]
This is a weird one, it looks like its happened after renaming one of my project files? Quitting Emacs has no effect

**Comment by domtronn** [comment]
Can you post your project file?

**Comment by domtronn** [comment]
The issue was using `eval-after-load` for package specific indent levels like `js2-mode` and `web-mode` meaning that the indent levels are only ever set once _(for whatever project you're currently in)_.

To solve this, when we call `projectable-set-indent-level`, check that `js2-mode` & `web-mode` functions are bound and then set the specific values.
